# vim:set ft=dockerfile:
FROM debian:stretch-slim
RUN groupadd -r core --gid=500 && useradd -g core --uid=500 -m -d /home/core core

# make the "en_US.UTF-8" locale
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        locales \
        curl \
        bzip2 \
        ca-certificates \
        fonts-liberation \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /etc/locale.alias /usr/share/locale/locale.alias \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV CONDA_DIR=/opt/conda \
    LANG=en_US.utf8 \
    LC_ALL=en_US.utf8 \
    PATH=$CONDA_DIR/bin:$PATH \
    MINICONDA_VERSION=4.3.21

RUN cd /tmp && \
    curl --silent -L -O https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "c1c15d3baba15bf50293ae963abef853 *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR && \
    rm Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    #$CONDA_DIR/bin/conda config --system --prepend channels conda-forge && \
    $CONDA_DIR/bin/conda config --system --set auto_update_conda false && \
    $CONDA_DIR/bin/conda config --system --set show_channel_urls true && \
    $CONDA_DIR/bin/conda update --all --quiet --yes && \
    $CONDA_DIR/bin/conda clean -tipsy

RUN $CONDA_DIR/bin/conda install --quiet --yes \
        'notebook=5.0.*' \
    && $CONDA_DIR/bin/conda clean -tipsy

CMD ["/bin/bash"]
